version: '2'
services:
  estudo:
    container_name: estudo
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
     - "10090:80"
    tty: true
    environment:
      TERM: xterm
    volumes:
     - ./:/opt/estudo
    command: php artisan serve --host=0.0.0.0 --port=80
networks:
  rino:
    external: true
    name: rino